import WorkspaceShell from "@/components/WorkspaceShell";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { AlertCircle, CheckCircle2, Database, Download, Loader2, RefreshCw, ShieldCheck } from "lucide-react";
import { toast } from "sonner";

export default function Admin() {
  const { user, loading } = useAuth();
  const owner = user?.role === "admin";
  const utils = trpc.useUtils();
  const imports = trpc.admin.imports.useQuery(undefined, { enabled: Boolean(owner) });
  const refresh = trpc.admin.refreshOfficialCompanies.useMutation({ onSuccess: async result => { toast.success(`已导入 ${result.recordCount.toLocaleString()} 家官方 HKSTP 公司，并构建 ${result.embeddingModel} 向量。`); await utils.profiles.counts.invalidate(); await utils.admin.imports.invalidate(); }, onError: error => toast.error(error.message) });
  if (!loading && !user) return <WorkspaceShell eyebrow="Owner controls" title="Official data refresh"><Access title="请先登录以验证所有者权限" action="登录" onClick={() => startLogin()} /></WorkspaceShell>;
  if (!loading && !owner) return <WorkspaceShell eyebrow="Owner controls" title="Official data refresh"><Access title="仅项目所有者可刷新官方公司目录" /></WorkspaceShell>;
  return <WorkspaceShell eyebrow="Owner controls" title="Official data refresh"><section className="rounded-[26px] bg-[#1d2b5b] p-6 text-white sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.15em] text-[#dbe4ff]"><Database className="size-3" /> data.gov.hk / HKSTP official API</div><h2 className="mt-5 text-2xl font-semibold tracking-[-.045em]">刷新唯一的 Company Match 数据源。</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#c5d0ef]">系统从 HKSTP 官方实时 JSON 接口拉取公司目录，转换并保存为 CSV，标准化资料，再通过 OpenRouter 生成 1024 维向量并替换现有公司索引。</p></div><Button onClick={() => refresh.mutate()} disabled={refresh.isPending} className="h-11 shrink-0 rounded-xl bg-white px-4 text-xs font-bold text-[#26366f] hover:bg-[#edf1ff]">{refresh.isPending ? <Loader2 className="mr-2 size-4 animate-spin" /> : <RefreshCw className="mr-2 size-4" />}刷新官方目录</Button></div></section><section className="mt-6 rounded-[22px] border border-[#e1e5ee] bg-white"><div className="border-b border-[#e9ecf2] px-5 py-4"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#8a94a8]">Provenance</p><h3 className="mt-1 text-sm font-semibold text-[#36405e]">官方刷新记录</h3></div>{imports.isLoading ? <div className="grid min-h-32 place-items-center"><Loader2 className="size-5 animate-spin text-[#5366ad]" /></div> : imports.isError ? <div className="p-7 text-center text-xs text-[#a16060]">导入记录无法加载。请刷新页面后重试。</div> : imports.data?.filter(item => item.sourceType === "company").length ? <div className="divide-y divide-[#edf0f4]">{imports.data.filter(item => item.sourceType === "company").map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 px-5 py-4"><div><p className="text-xs font-semibold text-[#3d4762]">{item.fileName}</p><p className="mt-1 text-[11px] text-[#7c8597]">{new Date(item.createdAt).toLocaleString()} · {item.recordCount.toLocaleString()} companies</p></div><span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-bold ${item.status === "ready" ? "bg-[#edf7f0] text-[#3b8a59]" : item.status === "failed" ? "bg-[#fff0f0] text-[#b65656]" : "bg-[#eff2fb] text-[#5568ae]"}`}>{item.status === "ready" ? <CheckCircle2 className="size-3" /> : <AlertCircle className="size-3" />}{item.status}</span></div>)}</div> : <div className="p-7 text-center text-xs text-[#8790a1]">尚未从官方 API 生成 Company Match 索引。</div>}</section></WorkspaceShell>;
}

function Access({ title, action, onClick }: { title: string; action?: string; onClick?: () => void }) { return <div className="grid min-h-[420px] place-items-center rounded-[26px] border border-dashed border-[#d8dce7] bg-white text-center"><div><ShieldCheck className="mx-auto size-7 text-[#7a8bc1]" /><h2 className="mt-4 text-lg font-semibold text-[#313b5c]">{title}</h2>{action && <Button onClick={onClick} className="mt-6 h-11 rounded-xl bg-[#1e2f65] px-4 text-xs font-bold text-white hover:bg-[#2a3d7e]">{action}</Button>}</div></div>; }
