import WorkspaceShell from "@/components/WorkspaceShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useLocale } from "@/contexts/LocaleContext";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Circle, Download, Loader2, Search, Sparkles, WandSparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

type Candidate = NonNullable<ReturnType<typeof trpc.companyMatch.recall.useMutation>["data"]>["candidates"][number];
type AnalysisResult = NonNullable<ReturnType<typeof trpc.companyMatch.analyzeCandidate.useMutation>["data"]>;

export default function CompanyMatch() {
  const { locale, t } = useLocale();
  const zh = locale === "zh";
  const [statement, setStatement] = useState("");
  const [refined, setRefined] = useState("");
  const [focus, setFocus] = useState<string[]>([]);
  const [dimensions, setDimensions] = useState({ capabilities: [] as string[], useCases: [] as string[], industryContext: [] as string[], geography: [] as string[], evidenceRequirements: [] as string[], retrievalTerms: [] as string[] });
  const [exclusions, setExclusions] = useState<string[]>([]);
  const [clarification, setClarification] = useState<string | null>(null);
  const [topK, setTopK] = useState(10);
  const [analyses, setAnalyses] = useState<Record<string, AnalysisResult | "running" | "failed">>({});
  const refine = trpc.companyMatch.refine.useMutation({ onSuccess: data => { setRefined(data.refinedStatement); setFocus(data.searchFocus); setDimensions({ capabilities: data.capabilities, useCases: data.useCases, industryContext: data.industryContext, geography: data.geography, evidenceRequirements: data.evidenceRequirements, retrievalTerms: data.retrievalTerms }); setExclusions(data.exclusions); setClarification(data.clarification); }, onError: error => toast.error(error.message) });
  const recall = trpc.companyMatch.recall.useMutation({ onSuccess: () => setAnalyses({}), onError: error => toast.error(error.message) });
  const analyze = trpc.companyMatch.analyzeCandidate.useMutation();
  const candidates = recall.data?.candidates ?? [];
  const analyzed = Object.values(analyses).filter((value): value is AnalysisResult => typeof value === "object");
  const retained = analyzed.filter(item => item.analysis.isSuitable && item.analysis.score >= 55);
  const analysisDone = candidates.length > 0 && Object.keys(analyses).length === candidates.length && !Object.values(analyses).includes("running");
  const progress = candidates.length ? Math.round((Object.keys(analyses).length / candidates.length) * 100) : 0;

  const optimize = () => { if (!statement.trim()) return toast.error(zh ? "请先描述你的公司需求。" : "Describe the company need first."); refine.mutate({ statement: statement.trim() }); };
  const runRecall = () => { if (!refined.trim()) return toast.error(zh ? "请先优化或填写用于检索的 statement。" : "Refine or enter a retrieval statement first."); recall.mutate({ refinedStatement: refined.trim(), topK }); };
  const runAnalysis = async () => {
    if (!candidates.length) return;
    setAnalyses({});
    for (const candidate of candidates) {
      setAnalyses(current => ({ ...current, [candidate.profile.id]: "running" }));
      try { const result = await analyze.mutateAsync({ refinedStatement: refined.trim(), profileId: candidate.profile.id, semanticSimilarity: candidate.similarity }); setAnalyses(current => ({ ...current, [candidate.profile.id]: result })); }
      catch { setAnalyses(current => ({ ...current, [candidate.profile.id]: "failed" })); }
    }
  };
  const exportCsv = () => {
    if (!retained.length) return;
    const header = zh ? ["公司", "HKSTP_集群", "网站", "语义相似度", "匹配分数", "分析结论", "优势证据", "资料缺口", "需核验", "核验查询"] : ["company", "cluster", "website", "semantic_similarity", "match_score", "rationale", "strengths", "gaps", "verification_needed", "verification_query"];
    const escape = (value: unknown) => `"${String(value ?? "").replace(/"/g, '""')}"`;
    const rows = retained.map(({ profile, semanticSimilarity, analysis }) => [profile.name, profile.sector, profile.website, semanticSimilarity.toFixed(4), analysis.score, analysis.rationale, analysis.strengths.join(" | "), analysis.gaps.join(" | "), analysis.verificationNeeded, analysis.verificationQuery].map(escape).join(","));
    const url = URL.createObjectURL(new Blob([[header.join(","), ...rows].join("\n")], { type: "text/csv;charset=utf-8" }));
    const link = document.createElement("a"); link.href = url; link.download = "company-match-validated-results.csv"; link.click(); URL.revokeObjectURL(url);
  };
  const stepState = useMemo(() => ({ refine: Boolean(refined), recall: candidates.length > 0, analyze: analysisDone, export: retained.length > 0 }), [refined, candidates.length, analysisDone, retained.length]);
  const steps = [{ label: t.stepRefine, done: stepState.refine }, { label: t.stepRecall, done: stepState.recall }, { label: t.stepAnalyze, done: stepState.analyze }, { label: t.stepExport, done: stepState.export }];

  return <WorkspaceShell eyebrow={t.officialDirectory} title={t.companyMatch}>
    <div className="mb-6 flex flex-wrap gap-2">{steps.map((step, index) => <div key={step.label} className={`inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-[11px] font-bold ${step.done ? "border-[#cfe5d6] bg-[#eef8f1] text-[#35734a]" : "border-[#e1e5ef] bg-white text-[#7a8499]"}`}>{step.done ? <CheckCircle2 className="size-3.5" /> : <Circle className="size-3.5" />}{step.label}</div>)}</div>
    <section className="rounded-[28px] bg-[#192654] p-6 text-white shadow-[0_20px_60px_rgba(24,38,84,.22)] sm:p-9"><div className="max-w-4xl"><div className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.14em] text-[#dce4ff]"><Sparkles className="size-3" /> {zh ? "深度需求优化" : "Deep request refinement"}</div><h2 className="mt-5 text-3xl font-semibold tracking-[-.055em] sm:text-4xl">{zh ? "描述你要找的公司。" : "Describe the company you need."}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#c8d2ef]">{zh ? "输入可以是简短关键词、完整需求文档或多段业务背景。系统会将目标能力、应用场景、行业、地域、证据要求和排除条件整理为更适合语义检索的 statement。" : "Use a short prompt, a detailed requirement document, or multi-paragraph business context. The system turns it into a semantic-search statement with capabilities, use cases, industries, geographies, evidence needs, and exclusions."}</p><div className="mt-6"><Textarea value={statement} onChange={event => setStatement(event.target.value)} placeholder={zh ? "例如：寻找为大型商业楼宇提供 AI 能源管理、物联网整合与可量化减碳能力的香港科技公司。也可直接粘贴完整需求说明。" : "For example: Find Hong Kong technology companies providing AI energy management, IoT integration, and measurable carbon reduction for large commercial buildings. You can also paste a full brief."} className="min-h-36 rounded-2xl border-white/15 bg-white/10 text-sm text-white placeholder:text-[#aebbe0] focus-visible:ring-[#9daefa]" /><Button onClick={optimize} disabled={refine.isPending} className="mt-3 h-11 rounded-xl bg-white px-4 text-xs font-bold text-[#273770] hover:bg-[#edf1ff]">{refine.isPending ? <Loader2 className="mr-2 size-4 animate-spin" /> : <WandSparkles className="mr-2 size-4" />}{t.refine}</Button></div></div></section>
    <section className="mt-6 rounded-[24px] border border-[#e2e6ef] bg-white p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end"><div className="flex-1"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#8690a6]">{zh ? "优化后的检索 statement（可编辑）" : "Refined retrieval statement (editable)"}</p><Textarea value={refined} onChange={event => setRefined(event.target.value)} placeholder={zh ? "先输入需求，再让 AI 生成更丰富的检索 statement。" : "Enter a requirement, then let AI build a richer retrieval statement."} className="mt-2 min-h-28 rounded-xl border-[#e1e5ee] bg-[#fbfcfe] text-sm" /></div><div className="w-full lg:w-40"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#8690a6]">{t.topK}</p><Input type="number" min={1} max={100} value={topK} onChange={event => setTopK(Math.max(1, Math.min(100, Number(event.target.value) || 10)))} className="mt-2 h-11 rounded-xl" /></div><Button onClick={runRecall} disabled={recall.isPending} className="h-11 rounded-xl bg-[#1f316a] px-4 text-xs font-bold text-white hover:bg-[#2b3f80]">{recall.isPending ? <Loader2 className="mr-2 size-4 animate-spin" /> : <Search className="mr-2 size-4" />}{t.recall}</Button></div>{(focus.length || exclusions.length || clarification || dimensions.capabilities.length) ? <div className="mt-4 grid gap-3 border-t border-[#edf0f4] pt-4 md:grid-cols-2 xl:grid-cols-3"><SignalGroup title={zh ? "目标信号" : "Target signals"} items={focus} tone="blue" /><SignalGroup title={zh ? "核心能力" : "Capabilities"} items={dimensions.capabilities} tone="blue" /><SignalGroup title={zh ? "应用场景" : "Use cases"} items={dimensions.useCases} tone="blue" /><SignalGroup title={zh ? "行业与地域" : "Industry & geography"} items={[...dimensions.industryContext, ...dimensions.geography]} tone="blue" /><SignalGroup title={zh ? "证据要求" : "Evidence requirements"} items={dimensions.evidenceRequirements} tone="amber" /><SignalGroup title={zh ? "检索术语" : "Retrieval terms"} items={dimensions.retrievalTerms} tone="blue" /><SignalGroup title={zh ? "排除条件" : "Exclusions"} items={exclusions} tone="amber" />{clarification && <div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#7785ad]">{zh ? "澄清建议" : "Clarification"}</p><p className="mt-1.5 text-xs leading-5 text-[#687288]">{clarification}</p></div>}</div> : null}</section>
    {recall.data && <section className="mt-6"><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#8690a6]">{t.candidate}</p><h2 className="mt-1 text-lg font-semibold text-[#263153]">{zh ? `已召回 ${candidates.length} 家公司，按语义相似度排序` : `${candidates.length} companies recalled by semantic similarity`}</h2></div><Button onClick={runAnalysis} disabled={!candidates.length || Object.values(analyses).includes("running")} className="h-10 rounded-xl bg-[#234064] px-4 text-xs font-bold text-white hover:bg-[#2d527e]">{Object.values(analyses).includes("running") ? <Loader2 className="mr-2 size-3.5 animate-spin" /> : <Sparkles className="mr-2 size-3.5" />}{t.analyze}</Button></div>{Object.values(analyses).includes("running") && <div className="mb-4 rounded-xl border border-[#dbe2f3] bg-[#f5f7fc] p-3"><div className="flex items-center justify-between text-xs font-semibold text-[#52658d]"><span>{zh ? "正在逐条分析候选公司" : "Analysing each recalled company"}</span><span>{progress}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#dce3f3]"><div className="h-full rounded-full bg-[#4d64b0] transition-all" style={{ width: `${progress}%` }} /></div></div>}<div className="grid gap-4 lg:grid-cols-2">{candidates.map(candidate => <CandidateCard key={candidate.profile.id} candidate={candidate} state={analyses[candidate.profile.id]} zh={zh} />)}</div></section>}
    {analysisDone && <section className="mt-6 rounded-[24px] border border-[#dce4f1] bg-white p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#8690a6]">{t.matches}</p><h2 className="mt-1 text-lg font-semibold text-[#263153]">{zh ? `${retained.length} 个通过 AI 筛选，${Math.max(0, candidates.length - retained.length)} 个已剔除` : `${retained.length} candidates passed AI validation; ${Math.max(0, candidates.length - retained.length)} excluded`}</h2></div><Button variant="outline" onClick={exportCsv} disabled={!retained.length} className="h-10 rounded-xl text-xs font-bold text-[#4357a2]"><Download className="mr-2 size-3.5" />{t.export}</Button></div></section>}
  </WorkspaceShell>;
}

function SignalGroup({ title, items, tone }: { title: string; items: string[]; tone: "blue" | "amber" }) { return <div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#7785ad]">{title}</p><div className="mt-2 flex flex-wrap gap-1.5">{items.length ? items.map(item => <span key={item} className={`rounded-md px-2 py-1 text-[10px] font-semibold ${tone === "blue" ? "bg-[#edf1fc] text-[#5065ad]" : "bg-[#fff5e7] text-[#a06d33]"}`}>{item}</span>) : <span className="text-xs text-[#9aa1b1]">—</span>}</div></div>; }

function CandidateCard({ candidate, state, zh }: { candidate: Candidate; state?: AnalysisResult | "running" | "failed"; zh: boolean }) {
  const result = state && typeof state === "object" ? state : null;
  return <article className={`rounded-[22px] border bg-white p-5 ${result?.analysis.isSuitable ? "border-[#cfe4d7]" : result ? "border-[#eadada]" : "border-[#e1e5ee]"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-[#273154]">{candidate.profile.name}</p><p className="mt-1 text-xs text-[#778197]">{candidate.profile.sector ?? "HKSTP company"}</p></div><div className="rounded-xl bg-[#edf1fc] px-3 py-2 text-right"><p className="text-[9px] font-bold uppercase tracking-[.12em] text-[#7180ae]">{zh ? "语义相似度" : "Similarity"}</p><p className="text-base font-bold text-[#354aa0]">{(candidate.similarity * 100).toFixed(1)}%</p></div></div>{state === "running" && <div className="mt-5 flex items-center gap-2 text-xs font-semibold text-[#5870b3]"><Loader2 className="size-4 animate-spin" />{zh ? "AI 正在核验资料与匹配度…" : "AI is validating the evidence and fit…"}</div>}{state === "failed" && <p className="mt-5 text-xs text-[#b26a6a]">{zh ? "该公司分析失败，可重新执行分析。" : "Analysis failed for this company. Run analysis again."}</p>}{result && <div className="mt-4"><div className="flex items-center justify-between"><p className={`text-xs font-bold ${result.analysis.isSuitable ? "text-[#3b8050]" : "text-[#ad6666]"}`}>{result.analysis.isSuitable ? (zh ? "保留" : "Retained") : (zh ? "已剔除" : "Excluded")}</p><p className="text-lg font-bold text-[#354aa0]">{result.analysis.score}%</p></div><p className="mt-3 text-xs leading-6 text-[#667087]">{result.analysis.rationale}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#4f7c61]">{zh ? "证据" : "Evidence"}</p>{result.analysis.strengths.map(item => <p key={item} className="mt-1.5 text-[11px] leading-5 text-[#657084]">• {item}</p>)}</div><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#a17643]">{zh ? "核验点" : "Checks"}</p>{result.analysis.gaps.map(item => <p key={item} className="mt-1.5 text-[11px] leading-5 text-[#657084]">• {item}</p>)}</div></div>{result.analysis.verificationNeeded && result.analysis.verificationQuery && <p className="mt-3 border-t border-[#edf0f4] pt-3 text-[10px] text-[#79849b]">{zh ? "建议核验：" : "Suggested validation: "}{result.analysis.verificationQuery}</p>}</div>}</article>;
}
