import WorkspaceShell from "@/components/WorkspaceShell";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { AlertCircle, ArrowRight, Building2, CircleDollarSign, Database, Search, Sparkles, Workflow } from "lucide-react";
import { Link } from "wouter";

const featureCards = [
  { icon: Building2, title: "Explore startups", body: "Browse verified HKSTP company and solution profiles.", href: "/profiles?type=company", tone: "blue" },
  { icon: CircleDollarSign, title: "Meet investors", body: "Filter investor mandates and find aligned capital.", href: "/profiles?type=investor", tone: "gold" },
  { icon: Search, title: "Describe the fit", body: "Use natural language to surface relevant profiles.", href: "/match", tone: "violet" },
];

export default function Home() {
  const counts = trpc.profiles.counts.useQuery();
  const values = counts.data ?? { company: 0, solution: 0, investor: 0 };
  const displayCount = (value: number) => counts.isLoading || counts.isError ? "—" : value.toLocaleString();
  return (
    <WorkspaceShell eyebrow="HKSTP ecosystem intelligence" title="Your next strategic introduction">
      <section className="relative overflow-hidden rounded-[28px] bg-[#192654] px-6 py-8 text-white shadow-[0_20px_60px_rgba(24,38,84,0.25)] sm:px-9 sm:py-10 lg:px-11">
        <img src="/manus-storage/hkstp-campus_50c4f169.jpg" alt="HKSTP campus" className="absolute inset-0 h-full w-full object-cover opacity-[0.13] mix-blend-screen" />
        <div className="absolute -right-16 -top-24 size-80 rounded-full bg-[#6578d8]/25 blur-3xl" /><div className="absolute bottom-[-140px] left-[35%] size-72 rounded-full bg-[#64a8cd]/15 blur-3xl" />
        <div className="relative max-w-3xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.16em] text-[#dce4ff]"><Sparkles className="size-3" /> AI-powered ecosystem matching</div><h2 className="max-w-2xl text-3xl font-semibold leading-[1.08] tracking-[-0.055em] sm:text-4xl">Where ambitious ventures meet conviction capital.</h2><p className="mt-5 max-w-xl text-sm leading-6 text-[#c9d2ed]">Navigate the active HKSTP startup, solution, and investor datasets with transparent, AI-assisted compatibility analysis.</p>{counts.isError && <div role="alert" className="mt-4 flex max-w-xl items-center gap-2 rounded-xl border border-[#ffc7c7]/35 bg-[#4b3156]/45 px-3 py-2.5 text-xs leading-5 text-[#ffe5e5]"><AlertCircle className="size-4 shrink-0" />Dataset totals are temporarily unavailable. You can still browse profiles or retry shortly.</div>}<div className="mt-7 flex flex-wrap gap-3"><Link href="/match"><Button className="h-11 rounded-xl bg-white px-4 text-xs font-bold text-[#26366f] hover:bg-[#ecf0ff]">Start a smart search <ArrowRight className="ml-2 size-3.5" /></Button></Link><Link href="/profiles?type=company"><Button variant="outline" className="h-11 rounded-xl border-white/20 bg-white/5 px-4 text-xs font-bold text-white hover:bg-white/10 hover:text-white">Browse the network</Button></Link></div></div>
        <div className="relative mt-9 grid max-w-2xl grid-cols-3 gap-3 border-t border-white/10 pt-5"><div><p className="text-xl font-semibold tracking-[-0.04em]">{displayCount(values.company)}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[0.12em] text-[#aebbdc]">Startups</p></div><div><p className="text-xl font-semibold tracking-[-0.04em]">{displayCount(values.solution)}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[0.12em] text-[#aebbdc]">Solutions</p></div><div><p className="text-xl font-semibold tracking-[-0.04em]">{displayCount(values.investor)}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[0.12em] text-[#aebbdc]">Investors</p></div></div>
      </section>
      <section className="mt-9"><div className="mb-4 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#8c95a9]">Quick access</p><h3 className="mt-1 text-lg font-semibold tracking-[-0.035em] text-[#202a4b]">Choose your route into the network</h3></div></div><div className="grid gap-4 md:grid-cols-3">{featureCards.map(card => <Link key={card.title} href={card.href} className="group rounded-[22px] border border-[#e4e7ef] bg-white p-5 transition-all hover:-translate-y-0.5 hover:shadow-[0_16px_38px_rgba(37,47,79,0.08)]"><div className={`grid size-10 place-items-center rounded-xl ${card.tone === "blue" ? "bg-[#ebf0ff] text-[#3c54a7]" : card.tone === "gold" ? "bg-[#fbf3e9] text-[#a36f35]" : "bg-[#f2edfb] text-[#7552a8]"}`}><card.icon className="size-5" /></div><h4 className="mt-5 text-sm font-semibold text-[#283151]">{card.title}</h4><p className="mt-2 text-xs leading-5 text-[#747e93]">{card.body}</p><span className="mt-5 inline-flex items-center gap-1 text-xs font-bold text-[#4156a2]">Open workspace <ArrowRight className="size-3.5 transition-transform group-hover:translate-x-1" /></span></Link>)}</div></section>
      <section className="mt-9 grid gap-4 lg:grid-cols-[1.4fr_0.9fr]"><div className="rounded-[22px] border border-[#e4e7ef] bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#8c95a9]">How it works</p><h3 className="mt-1 text-base font-semibold tracking-[-0.03em] text-[#242d4e]">Make higher-context introductions</h3></div><Workflow className="size-5 text-[#6074ba]" /></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><div><span className="grid size-6 place-items-center rounded-full bg-[#edf0fb] text-[10px] font-bold text-[#465ba7]">01</span><p className="mt-3 text-xs font-bold text-[#3a4563]">Choose a profile</p><p className="mt-1 text-[11px] leading-5 text-[#7d8597]">Start with a company, solution, or investor.</p></div><div><span className="grid size-6 place-items-center rounded-full bg-[#edf0fb] text-[10px] font-bold text-[#465ba7]">02</span><p className="mt-3 text-xs font-bold text-[#3a4563]">Review ranked fit</p><p className="mt-1 text-[11px] leading-5 text-[#7d8597]">AI compares strategic signals across the active data.</p></div><div><span className="grid size-6 place-items-center rounded-full bg-[#edf0fb] text-[10px] font-bold text-[#465ba7]">03</span><p className="mt-3 text-xs font-bold text-[#3a4563]">Prepare the conversation</p><p className="mt-1 text-[11px] leading-5 text-[#7d8597]">Use evidence-based talking points to lead outreach.</p></div></div></div><div className="relative overflow-hidden rounded-[22px] border border-[#dfe4f1] bg-[#edf0fa] p-5 sm:p-6"><Database className="absolute -bottom-6 -right-5 size-32 text-[#cfd6ed]" /><p className="relative text-[10px] font-bold uppercase tracking-[0.16em] text-[#6777af]">Dataset status</p><h3 className="relative mt-2 max-w-[230px] text-base font-semibold tracking-[-0.035em] text-[#273665]">Grounded in the current imported sources</h3><p className="relative mt-3 max-w-[280px] text-xs leading-5 text-[#68759e]">Profile browsing and matching are powered by the three provided HKSTP data files.</p><Link href="/admin" className="relative mt-5 inline-flex items-center gap-1 text-xs font-bold text-[#41569f]">View sources <ArrowRight className="size-3.5" /></Link></div></section>
    </WorkspaceShell>
  );
}
